import { Inter } from 'next/font/google'
//import './globals.css'
import 'bootstrap/dist/css/bootstrap.css'
import '@fortawesome/fontawesome-free/css/all.min.css';
import NavScroll from '../../../components/admin/NavScroll';


//import NavScroll from '@/components/admin/NavScroll'

const inter = Inter({ subsets: ['latin'] })
const metadata = {
title: 'Create Next App',
description: 'Generated by create next app',
}
export default function RootLayout({ children }) {
return (
<html lang="en">
<body className={inter.className}>
<NavScroll/>
{children}
</body>
</html>
)
}